# 这里是自动版本检测URL
Get.Core.Update.AllVersion=https://api.github.com/repos/deng-rui/RW-HPS/releases
Get.Core.Update.UpdateLastVersion=https://api.github.com/repos/deng-rui/RW-HPS/releases/latest
Get.JSLib.Update.UpdateLastVersion=https://api.github.com/repos/deng-rui/RW-HPS-JSLib/releases/latest
#Get Game-Res
Get.Core.ResDown = https://jsdelivr.rwhps.net/gh/deng-rui/RW-HPS-ResFile@1.15_3.0.0_6/
#GetPlugin
Get.Plugin.Core = https://plugin.data.der.kim/



